<?php
	/*
    Developed by Sitegurus
    Manthan Vora<manthan18121989@gmail.com>*/
    $rules = Mage::getModel('rules/rules')->getCollection();
    $current_product = Mage::registry('current_product');
    $procut_ids = Mage::registry('current_product')->getCategoryIds();
    foreach($rules as $rule){
        $rule_category = $rule->getData('category_name');
        if(in_array($rule_category,$procut_ids)){
        ?>
        <div class="block block-category">
            <div class="block-title">
                <strong>
                    <span>Product's Features</span>
                </strong>
            </div>
            <div class="block-content block-category-content">
                <div class="shipping-block">
                <?php if($rule->getData('shipping_method') == "Free Shipping"){?>
                    <div class="free-shipping"><?php echo $rule->getData('shipping_method')." is available" ?></div>
                <?php } else{ ?>
                    <div class="paid-shipping"><?php echo "Only ".$rule->getData('shipping_method')." is available" ?></div>
                <?php }?>
                </div>
                <div class="payment-block">
                <?php if($rule->getData('payment_method') == "Pre/Post Payment"){?>
                    <div class="pre-post-payment"><?php echo $rule->getData('payment_method')." Methods are available"?></div>
                <?php } else{ ?>
                    <div class="pre-payment"><?php echo $rule->getData('payment_method')." Method is available"?></div>
                <?php } ?>
                </div>
                <div class="return-block">
                <?php if($rule->getData('return_method') == "Not Available"){?>
                    <div class="no-return"><?php echo "Return is ".$rule->getData('return_method') ?></div>
                <?php } else if($rule->getData('return_method') == "Paid Return"){?>
                <div class="paid-return"><?php echo $rule->getData('return_method')." is available" ?></div>
                <?php } else {?>
                <div class="free-return"><?php echo $rule->getData('return_method')." is available" ?></div>
                <?php } ?>
                </div>
            </div>
        </div>
     <?php break; }
    }
?>